name       : setxkbmap
version    : 1.3.1
release    : 3
source     :
    - http://xorg.freedesktop.org/releases/individual/app/setxkbmap-1.3.1.tar.bz2 : a9ddb3963f263ba13f0ea105d8c45a531832140530217cc559587bb94f02d3e1
license    : GPL-3.0
component  : xorg.apps
summary    : X.Org Applications - setxkbmap
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xkbfile)
description: |
    X.Org Applications - setxkbmap
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
