name       : setxkbmap
version    : 1.3.2
release    : 4
source     :
    - https://xorg.freedesktop.org/releases/individual/app/setxkbmap-1.3.2.tar.gz : 7e934afc55f161406f7dd99b5be8837e5d1478d8263776697b159d48461a1d3c
license    : GPL-3.0
component  : xorg.apps
summary    : X.Org Applications - setxkbmap
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xkbfile)
description: |
    X.Org Applications - setxkbmap
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
