name       : setxkbmap
version    : 1.3.3
release    : 5
source     :
    - https://xorg.freedesktop.org/releases/individual/app/setxkbmap-1.3.3.tar.gz : 51ba28edf93a464a7444b53b154fd5e93dedd1e9bbcc85b636f4cf56986c4842
license    : GPL-3.0
component  : xorg.apps
summary    : X11 client to change the keymaps in the X server for a specified keyboard
description: |
    setxkbmap is an X11 client to change the keymaps in the X server for a specified keyboard to use the layout determined by the options listed on the command line
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xkbfile)
    - pkgconfig(xrandr)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
